@extends('layouts.main')
   @section('content')
    <div class="container-xxl py-5">
      <div class="container">
      <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;"><span style="box-sizing: border-box; font-weight: bolder; background: transparent !important;"><span style="box-sizing: border-box; background: transparent !important; font-size: 26px;"><span style="box-sizing: border-box; background: transparent !important; font-family: Arial !important;" data-custom-class="title">SHIPPING &amp; DELIVERY POLICY</span></span></span></div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">&nbsp;</div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; font-weight: bolder; background: transparent !important;"><span style="box-sizing: border-box; background: transparent !important; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-family: Arial !important; color: #595959 !important; font-size: 14px !important;" data-custom-class="subtitle">Last updated&nbsp;September 21, 2023</span></span></span></span></div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">&nbsp;</div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">&nbsp;</div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">&nbsp;</div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; line-height: 1.5; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">This Shipping &amp; Delivery Policy is part of our&nbsp;Terms and Conditions&nbsp;("Terms") and should be therefore read alongside our main Terms:&nbsp;<a style="box-sizing: border-box; background: transparent !important; color: #3030f1 !important; word-break: break-word !important;" href="../terms-conditions" target="_blank" rel="noopener" data-custom-class="link">https://hotels.sivalikagroup.com/terms-conditions</a>.</span></span></span></div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; line-height: 1.5; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">&nbsp;</div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; line-height: 1.5; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">&nbsp;</div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; line-height: 1.5; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">Please carefully review our Shipping &amp; Delivery Policy when purchasing our products. This policy will apply to any order you place with us.</span></span></span></div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; line-height: 1.5; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">&nbsp;</div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; line-height: 1.5; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;"><span style="box-sizing: border-box; background: transparent !important; font-family: Arial !important; font-size: 19px !important;" data-custom-class="heading_1"><span style="box-sizing: border-box; font-weight: bolder; background: transparent !important;"><span style="box-sizing: border-box; color: #7f7f7f; background: transparent !important;"><span style="box-sizing: border-box; font-size: 15px; color: #595959; background: transparent !important;"><span style="box-sizing: border-box; background: transparent !important; font-size: 19px !important; color: #000000 !important;" data-custom-class="heading_1"><span style="box-sizing: border-box; font-weight: bolder; background: transparent !important;">WHAT ARE MY SHIPPING &amp; DELIVERY OPTIONS?</span></span></span></span></span></span></div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; line-height: 1.5; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">&nbsp;</div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; line-height: 1.5; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">We offer various shipping options. In some cases a third-party supplier may be managing our inventory and will be responsible for shipping your products.</span></span></span></div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; line-height: 1.5; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">&nbsp;</div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; line-height: 1.5; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;"><span style="box-sizing: border-box; font-weight: bolder; background: transparent !important;"><span style="box-sizing: border-box; background: transparent !important; font-family: Arial !important; font-size: 17px !important;" data-custom-class="heading_2">Shipping Fees</span></span></div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; line-height: 1.5; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">&nbsp;</div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">We&nbsp;offer&nbsp;shipping at the following rates:</span></span></span></div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;">&nbsp;</div>
        <table style="width: 416.141px; margin-right: 529.641px; background: transparent !important;">
        <tbody style="box-sizing: border-box; background: transparent !important;">
        <tr style="box-sizing: border-box; background: transparent !important;">
        <td style="box-sizing: border-box; background: transparent !important; width: 237.375px; border-bottom: 1px solid black;">
        <div style="box-sizing: border-box; background: transparent !important; text-align: center; line-height: 1;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text"><span style="box-sizing: border-box; font-weight: bolder; background: transparent !important;">Shipping Method</span></span></span></span></div>
        <div style="box-sizing: border-box; background: transparent !important; text-align: center; line-height: 1;">&nbsp;</div>
        </td>
        <td style="box-sizing: border-box; background: transparent !important; width: 172.766px; border-bottom: 1px solid black;">
        <div style="box-sizing: border-box; background: transparent !important; text-align: center; line-height: 1;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text"><span style="box-sizing: border-box; font-weight: bolder; background: transparent !important;">Shipping Fee</span></span></span></span></div>
        <div style="box-sizing: border-box; background: transparent !important; text-align: center; line-height: 1;">&nbsp;</div>
        </td>
        </tr>
        </tbody>
        </table>
        </div>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; line-height: 1; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">&nbsp;</div>
        <table style="background-color: #ffffff; font-family: sans-serif; width: 416.141px; margin-right: 529.641px; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">
        <tbody style="box-sizing: border-box; background: transparent !important;">
        <tr style="box-sizing: border-box; background: transparent !important;">
        <td style="box-sizing: border-box; background: transparent !important; width: 237.375px;">
        <div style="box-sizing: border-box; background: transparent !important; text-align: center; line-height: 1;">&nbsp;</div>
        <div style="box-sizing: border-box; background: transparent !important; text-align: center; line-height: 1;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">__________</span></span></span></div>
        <div style="box-sizing: border-box; background: transparent !important; text-align: center; line-height: 1.4;">&nbsp;</div>
        </td>
        <td style="box-sizing: border-box; background: transparent !important; width: 172.766px; text-align: center; line-height: 1;"><br style="box-sizing: border-box; background: transparent !important;" /><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">__________</span></span></span></td>
        </tr>
        </tbody>
        </table>
        <div style="box-sizing: border-box; background-color: #ffffff; font-family: sans-serif; background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;">
        <div style="box-sizing: border-box; background: transparent !important;">
        <div style="box-sizing: border-box; background: transparent !important;">
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;">&nbsp;</div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;">&nbsp;</div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">All times and dates given for delivery of the products are given in good faith but are estimates only.</span></span></span></div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;">&nbsp;</div>
        <div style="box-sizing: border-box; background: transparent !important;">
        <div style="box-sizing: border-box; background: transparent !important;">
        <div style="box-sizing: border-box; background: transparent !important;">
        <div style="box-sizing: border-box; background: transparent !important;">
        <div style="box-sizing: border-box; background: transparent !important;">
        <div style="box-sizing: border-box; background: transparent !important;">
        <div style="box-sizing: border-box; background: transparent !important;">
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-family: Arial !important; font-size: 19px !important; color: #000000 !important;" data-custom-class="heading_1"><span style="box-sizing: border-box; font-weight: bolder; background: transparent !important;">DO YOU DELIVER INTERNATIONALLY?</span></span></span></span></div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        <div style="box-sizing: border-box; background: transparent !important;">
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;">&nbsp;</div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">We do not offer international shipping.</span></span></span></div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;">&nbsp;</div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-family: Arial !important; font-size: 19px !important; color: #000000 !important;" data-custom-class="heading_1"><span style="box-sizing: border-box; font-weight: bolder; background: transparent !important;">WHAT HAPPENS IF MY ORDER IS DELAYED?</span></span></span></span></div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;">&nbsp;</div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">If delivery is delayed for any reason we will let you know as soon as possible and will advise you of a revised estimated date for delivery.</span></span></span></div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;">&nbsp;</div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-family: Arial !important; font-size: 19px !important; color: #000000 !important;" data-custom-class="heading_1"><span style="box-sizing: border-box; font-weight: bolder; background: transparent !important;">QUESTIONS ABOUT RETURNS?</span></span></span></span></div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;">&nbsp;</div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">If you have questions about returns, please review our Return Policy:&nbsp;<a style="box-sizing: border-box; background: transparent !important; color: #3030f1 !important; word-break: break-word !important;" href="../refund-cancellation" target="_blank" rel="noopener" data-custom-class="link">https://hotels.sivalikagroup.com/refund-cancellation</a>.</span></span></span></div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;">&nbsp;</div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-family: Arial !important; font-size: 19px !important; color: #000000 !important;" data-custom-class="heading_1"><span style="box-sizing: border-box; font-weight: bolder; background: transparent !important;">HOW CAN YOU CONTACT US ABOUT THIS POLICY?</span></span></span></span></div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;">&nbsp;</div>
        <div style="box-sizing: border-box; background: transparent !important; line-height: 1.5;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">If you have any further questions or comments, you may contact us by:</span></span></span></div>
        <ul style="box-sizing: border-box; list-style-type: square; background: transparent !important;">
        <li style="box-sizing: border-box; background: transparent !important; line-height: 1.5;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">Phone:&nbsp;8582830483</span></span></span></li>
        </ul>
        <div style="box-sizing: border-box; background: transparent !important;">&nbsp;</div>
        <ul style="box-sizing: border-box; list-style-type: square; background: transparent !important;">
        <li style="box-sizing: border-box; background: transparent !important;"><span style="box-sizing: border-box; background: transparent !important; font-size: 15px; color: #595959;"><span style="box-sizing: border-box; background: transparent !important;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">Email:&nbsp;sivalikagroup@gmail.com</span></span></span></li>
        </ul>
        <div style="box-sizing: border-box; background: transparent !important;">&nbsp;</div>
        <ul style="box-sizing: border-box; list-style-type: square; background: transparent !important;">
        <li style="box-sizing: border-box; background: transparent !important;"><span style="box-sizing: border-box; background: transparent !important; color: #7f7f7f;"><span style="box-sizing: border-box; background: transparent !important; color: #595959; font-size: 15px;"><span style="box-sizing: border-box; background: transparent !important; font-size: 14px !important; font-family: Arial !important;" data-custom-class="body_text">Online contact form:&nbsp;<a style="box-sizing: border-box; background: transparent !important; color: #3030f1 !important; word-break: break-word !important;" href="../contact-us" target="_blank" rel="noopener" data-custom-class="link">https://hotels.sivalikagroup.com/contact-us</a></span></span></span></li>
        </ul>
        </div>
        </div>
        </div>
        </div>
      </div>
    </div>
   @endsection
@section('script')
@endsection